import Head from "next/head"
import { Nav } from "../components/Nav/Nav"

export default function Home() {
  return (
    <>
      <Head key={""}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
    </>
  )
}
