import Head from "next/head"
import { Banner } from "../components/Banner/Banner"
import { LandingProductBar } from "../components/LandingProductBar/LandingProductBar"
import { MainLayout } from "../components/MainLayout/MainLayout"

import { useAllProductsShowcaseQuery } from "../generated/graphql"

export default function Home() {
  const { data } = useAllProductsShowcaseQuery()
  console.log(data)

  return (
    <>
      <Head key={""}>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Banner />
        <LandingProductBar header="Recommended for you" />
        <LandingProductBar header="Discounted products" />
      </MainLayout>
    </>
  )
}
